all:
  children:
    docker_nodes:
      vars:
        platform_family: Debian
        platform_distribution: Debian
        platform_distribution_major_version: "12"

      hosts:
        ansible-node1:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3

        ansible-node2:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3