all:
  children:
    docker_nodes:
      hosts:
        ansible-node1:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3

        ansible-node2:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3
