all:
  children:

    linux:
      children:
        ubuntu:
          hosts:
            ubuntu-node1:
              ansible_host: 192.168.56.11

        rhel:
          hosts:
            rhel-node1:
              ansible_host: 192.168.56.12
        
        suse:
          hosts:
            suse-node1:
              ansible_host: 192.168.56.14
    local:
      hosts:
        localhost:
          ansible_connection: local
